// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnbtUaig83aqAQUHjuEXq7J-3cF7bvxK8',
    appId: '1:55120087662:web:f4f5a790ea0f85fd61747f',
    messagingSenderId: '55120087662',
    projectId: 'instagram-6bd5b',
    authDomain: 'instagram-6bd5b.firebaseapp.com',
    storageBucket: 'instagram-6bd5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmJoTDvDJ5K9pDKEeQPRBum-_ZhzR8GkM',
    appId: '1:55120087662:android:73f7564f82cf696b61747f',
    messagingSenderId: '55120087662',
    projectId: 'instagram-6bd5b',
    storageBucket: 'instagram-6bd5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr1qz8uML9CiwIlbzuvv11-hBkyeqRFys',
    appId: '1:55120087662:ios:c105b65f1c52ce5561747f',
    messagingSenderId: '55120087662',
    projectId: 'instagram-6bd5b',
    storageBucket: 'instagram-6bd5b.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr1qz8uML9CiwIlbzuvv11-hBkyeqRFys',
    appId: '1:55120087662:ios:28eb423d9b24b0cf61747f',
    messagingSenderId: '55120087662',
    projectId: 'instagram-6bd5b',
    storageBucket: 'instagram-6bd5b.appspot.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
